package com.example.touristguide.core.enums

enum class ActivityActionType { LOGIN, ADD_PLACE, ADD_REVIEW, ADD_PHOTO, ADD_FAVORITE, REMOVE_FAVORITE, REPORT, APPROVE_CONTENT, REJECT_CONTENT, POINTS_ADDED, ACHIEVEMENT_UNLOCKED, TASK_COMPLETED }
